apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: store-daemon
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: store-daemon
  template:
    metadata:
      labels:
        app: store-daemon
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: store-daemon
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CACHE_URL
              value: {{ .Values.cacheUrl }}
          volumeMounts:
            - name: nix-store
              mountPath: /nix/store
            - name: mounts
              mountPath: /var/lib/nixfs/mounts
      volumes:
        - name: nix-store
          hostPath:
            path: /var/lib/nixfs/store
            type: DirectoryOrCreate
        - name: mounts
          hostPath:
            path: /var/lib/nixfs/mounts
            type: DirectoryOrCreate
