image:
  repository: ghcr.io/general-intelligence-systems/nix-store-operator
  tag: latest
  pullPolicy: IfNotPresent

cacheUrl: https://cache.nixos.org

serviceAccount:
  name: store-daemon

namespace: nix-system
